#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceMaker
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InvoiceMakerDB")]
	public partial class InvoiceMakerDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInvoice(Invoice instance);
    partial void UpdateInvoice(Invoice instance);
    partial void DeleteInvoice(Invoice instance);
    partial void InsertItems(Items instance);
    partial void UpdateItems(Items instance);
    partial void DeleteItems(Items instance);
    partial void InsertTraders(Traders instance);
    partial void UpdateTraders(Traders instance);
    partial void DeleteTraders(Traders instance);
    partial void InsertBuyers(Buyers instance);
    partial void UpdateBuyers(Buyers instance);
    partial void DeleteBuyers(Buyers instance);
    partial void InsertPrivatePersons(PrivatePersons instance);
    partial void UpdatePrivatePersons(PrivatePersons instance);
    partial void DeletePrivatePersons(PrivatePersons instance);
    partial void InsertSellers(Sellers instance);
    partial void UpdateSellers(Sellers instance);
    partial void DeleteSellers(Sellers instance);
    #endregion
		
		public InvoiceMakerDBDataContext() : 
				base(global::InvoiceMaker.Properties.Settings.Default.InvoiceMakerDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceMakerDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceMakerDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceMakerDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InvoiceMakerDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
		
		public System.Data.Linq.Table<Items> Items
		{
			get
			{
				return this.GetTable<Items>();
			}
		}
		
		public System.Data.Linq.Table<Traders> Traders
		{
			get
			{
				return this.GetTable<Traders>();
			}
		}
		
		public System.Data.Linq.Table<Buyers> Buyers
		{
			get
			{
				return this.GetTable<Buyers>();
			}
		}
		
		public System.Data.Linq.Table<PrivatePersons> PrivatePersons
		{
			get
			{
				return this.GetTable<PrivatePersons>();
			}
		}
		
		public System.Data.Linq.Table<Sellers> Sellers
		{
			get
			{
				return this.GetTable<Sellers>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoices")]
	public partial class Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Number;
		
		private System.DateTime _IssueDate;
		
		private System.DateTime _SaleDate;
		
		private string _Place;
		
		private System.Nullable<int> _SellerId;
		
		private System.Nullable<int> _BuyerId;
		
		private string _BuyerType;
		
		private string _PaymentType;
		
		private string _PaymentDeadline;
		
		private string _SellerSignature;
		
		private string _BuyerSignature;
		
		private string _Notes;
		
		private EntitySet<Items> _Items;
		
		private EntityRef<Buyers> _Buyer;
		
		private EntityRef<Sellers> _Seller;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnIssueDateChanging(System.DateTime value);
    partial void OnIssueDateChanged();
    partial void OnSaleDateChanging(System.DateTime value);
    partial void OnSaleDateChanged();
    partial void OnPlaceChanging(string value);
    partial void OnPlaceChanged();
    partial void OnSellerIdChanging(System.Nullable<int> value);
    partial void OnSellerIdChanged();
    partial void OnBuyerIdChanging(System.Nullable<int> value);
    partial void OnBuyerIdChanged();
    partial void OnBuyerTypeChanging(string value);
    partial void OnBuyerTypeChanged();
    partial void OnPaymentTypeChanging(string value);
    partial void OnPaymentTypeChanged();
    partial void OnPaymentDeadlineChanging(string value);
    partial void OnPaymentDeadlineChanged();
    partial void OnSellerSignatureChanging(string value);
    partial void OnSellerSignatureChanged();
    partial void OnBuyerSignatureChanging(string value);
    partial void OnBuyerSignatureChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Invoice()
		{
			this._Items = new EntitySet<Items>(new Action<Items>(this.attach_Items), new Action<Items>(this.detach_Items));
			this._Buyer = default(EntityRef<Buyers>);
			this._Seller = default(EntityRef<Sellers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueDate", DbType="Date NOT NULL")]
		public System.DateTime IssueDate
		{
			get
			{
				return this._IssueDate;
			}
			set
			{
				if ((this._IssueDate != value))
				{
					this.OnIssueDateChanging(value);
					this.SendPropertyChanging();
					this._IssueDate = value;
					this.SendPropertyChanged("IssueDate");
					this.OnIssueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleDate", DbType="Date NOT NULL")]
		public System.DateTime SaleDate
		{
			get
			{
				return this._SaleDate;
			}
			set
			{
				if ((this._SaleDate != value))
				{
					this.OnSaleDateChanging(value);
					this.SendPropertyChanging();
					this._SaleDate = value;
					this.SendPropertyChanged("SaleDate");
					this.OnSaleDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Place", DbType="NVarChar(100)")]
		public string Place
		{
			get
			{
				return this._Place;
			}
			set
			{
				if ((this._Place != value))
				{
					this.OnPlaceChanging(value);
					this.SendPropertyChanging();
					this._Place = value;
					this.SendPropertyChanged("Place");
					this.OnPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerId", DbType="Int")]
		public System.Nullable<int> SellerId
		{
			get
			{
				return this._SellerId;
			}
			set
			{
				if ((this._SellerId != value))
				{
					if (this._Seller.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSellerIdChanging(value);
					this.SendPropertyChanging();
					this._SellerId = value;
					this.SendPropertyChanged("SellerId");
					this.OnSellerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerId", DbType="Int")]
		public System.Nullable<int> BuyerId
		{
			get
			{
				return this._BuyerId;
			}
			set
			{
				if ((this._BuyerId != value))
				{
					if (this._Buyer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBuyerIdChanging(value);
					this.SendPropertyChanging();
					this._BuyerId = value;
					this.SendPropertyChanged("BuyerId");
					this.OnBuyerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerType", DbType="NVarChar(50)")]
		public string BuyerType
		{
			get
			{
				return this._BuyerType;
			}
			set
			{
				if ((this._BuyerType != value))
				{
					this.OnBuyerTypeChanging(value);
					this.SendPropertyChanging();
					this._BuyerType = value;
					this.SendPropertyChanged("BuyerType");
					this.OnBuyerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType", DbType="NVarChar(50)")]
		public string PaymentType
		{
			get
			{
				return this._PaymentType;
			}
			set
			{
				if ((this._PaymentType != value))
				{
					this.OnPaymentTypeChanging(value);
					this.SendPropertyChanging();
					this._PaymentType = value;
					this.SendPropertyChanged("PaymentType");
					this.OnPaymentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDeadline", DbType="NVarChar(50)")]
		public string PaymentDeadline
		{
			get
			{
				return this._PaymentDeadline;
			}
			set
			{
				if ((this._PaymentDeadline != value))
				{
					this.OnPaymentDeadlineChanging(value);
					this.SendPropertyChanging();
					this._PaymentDeadline = value;
					this.SendPropertyChanged("PaymentDeadline");
					this.OnPaymentDeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerSignature", DbType="NVarChar(255)")]
		public string SellerSignature
		{
			get
			{
				return this._SellerSignature;
			}
			set
			{
				if ((this._SellerSignature != value))
				{
					this.OnSellerSignatureChanging(value);
					this.SendPropertyChanging();
					this._SellerSignature = value;
					this.SendPropertyChanged("SellerSignature");
					this.OnSellerSignatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyerSignature", DbType="NVarChar(255)")]
		public string BuyerSignature
		{
			get
			{
				return this._BuyerSignature;
			}
			set
			{
				if ((this._BuyerSignature != value))
				{
					this.OnBuyerSignatureChanging(value);
					this.SendPropertyChanging();
					this._BuyerSignature = value;
					this.SendPropertyChanged("BuyerSignature");
					this.OnBuyerSignatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Invoice_Item", Storage="_Items", ThisKey="Id", OtherKey="InvoiceId")]
		public EntitySet<Items> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Buyers_Invoice", Storage="_Buyer", ThisKey="BuyerId", OtherKey="Id", IsForeignKey=true)]
		public Buyers Buyers
		{
			get
			{
				return this._Buyer.Entity;
			}
			set
			{
				Buyers previousValue = this._Buyer.Entity;
				if (((previousValue != value) 
							|| (this._Buyer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Buyer.Entity = null;
						previousValue.Invoices.Remove(this);
					}
					this._Buyer.Entity = value;
					if ((value != null))
					{
						value.Invoices.Add(this);
						this._BuyerId = value.Id;
					}
					else
					{
						this._BuyerId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Buyers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sellers_Invoice", Storage="_Seller", ThisKey="SellerId", OtherKey="Id", IsForeignKey=true)]
		public Sellers Sellers
		{
			get
			{
				return this._Seller.Entity;
			}
			set
			{
				Sellers previousValue = this._Seller.Entity;
				if (((previousValue != value) 
							|| (this._Seller.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seller.Entity = null;
						previousValue.Invoices.Remove(this);
					}
					this._Seller.Entity = value;
					if ((value != null))
					{
						value.Invoices.Add(this);
						this._SellerId = value.Id;
					}
					else
					{
						this._SellerId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sellers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Items(Items entity)
		{
			this.SendPropertyChanging();
			entity.Invoice = this;
		}
		
		private void detach_Items(Items entity)
		{
			this.SendPropertyChanging();
			entity.Invoice = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Items : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _InvoiceId;
		
		private string _Name;
		
		private int _Quantity;
		
		private string _Unit;
		
		private string _VAT;
		
		private decimal _Netto;
		
		private decimal _Brutto;
		
		private EntityRef<Invoice> _Invoice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnInvoiceIdChanging(System.Nullable<int> value);
    partial void OnInvoiceIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    partial void OnVATChanging(string value);
    partial void OnVATChanged();
    partial void OnNettoChanging(decimal value);
    partial void OnNettoChanged();
    partial void OnBruttoChanging(decimal value);
    partial void OnBruttoChanged();
    #endregion
		
		public Items()
		{
			this._Invoice = default(EntityRef<Invoice>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceId", DbType="Int")]
		public System.Nullable<int> InvoiceId
		{
			get
			{
				return this._InvoiceId;
			}
			set
			{
				if ((this._InvoiceId != value))
				{
					if (this._Invoice.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInvoiceIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceId = value;
					this.SendPropertyChanged("InvoiceId");
					this.OnInvoiceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="NVarChar(10)")]
		public string VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this.OnVATChanging(value);
					this.SendPropertyChanging();
					this._VAT = value;
					this.SendPropertyChanged("VAT");
					this.OnVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Netto", DbType="Decimal(18,2) NOT NULL")]
		public decimal Netto
		{
			get
			{
				return this._Netto;
			}
			set
			{
				if ((this._Netto != value))
				{
					this.OnNettoChanging(value);
					this.SendPropertyChanging();
					this._Netto = value;
					this.SendPropertyChanged("Netto");
					this.OnNettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brutto", DbType="Decimal(18,2) NOT NULL")]
		public decimal Brutto
		{
			get
			{
				return this._Brutto;
			}
			set
			{
				if ((this._Brutto != value))
				{
					this.OnBruttoChanging(value);
					this.SendPropertyChanging();
					this._Brutto = value;
					this.SendPropertyChanged("Brutto");
					this.OnBruttoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Invoice_Item", Storage="_Invoice", ThisKey="InvoiceId", OtherKey="Id", IsForeignKey=true)]
		public Invoice Invoice
		{
			get
			{
				return this._Invoice.Entity;
			}
			set
			{
				Invoice previousValue = this._Invoice.Entity;
				if (((previousValue != value) 
							|| (this._Invoice.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Invoice.Entity = null;
						previousValue.Items.Remove(this);
					}
					this._Invoice.Entity = value;
					if ((value != null))
					{
						value.Items.Add(this);
						this._InvoiceId = value.Id;
					}
					else
					{
						this._InvoiceId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Invoice");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Traders")]
	public partial class Traders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _VATID;
		
		private string _StreetAndNo;
		
		private string _Postcode;
		
		private string _City;
		
		private string _TraderType;
		
		private EntitySet<Buyers> _Buyers;
		
		private EntitySet<PrivatePersons> _PrivatePersons;
		
		private EntitySet<Sellers> _Sellers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnVATIDChanging(string value);
    partial void OnVATIDChanged();
    partial void OnStreetAndNoChanging(string value);
    partial void OnStreetAndNoChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnTraderTypeChanging(string value);
    partial void OnTraderTypeChanged();
    #endregion
		
		public Traders()
		{
			this._Buyers = new EntitySet<Buyers>(new Action<Buyers>(this.attach_Buyers), new Action<Buyers>(this.detach_Buyers));
			this._PrivatePersons = new EntitySet<PrivatePersons>(new Action<PrivatePersons>(this.attach_PrivatePersons), new Action<PrivatePersons>(this.detach_PrivatePersons));
			this._Sellers = new EntitySet<Sellers>(new Action<Sellers>(this.attach_Sellers), new Action<Sellers>(this.detach_Sellers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string VATID
		{
			get
			{
				return this._VATID;
			}
			set
			{
				if ((this._VATID != value))
				{
					this.OnVATIDChanging(value);
					this.SendPropertyChanging();
					this._VATID = value;
					this.SendPropertyChanged("VATID");
					this.OnVATIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAndNo", DbType="NVarChar(255)")]
		public string StreetAndNo
		{
			get
			{
				return this._StreetAndNo;
			}
			set
			{
				if ((this._StreetAndNo != value))
				{
					this.OnStreetAndNoChanging(value);
					this.SendPropertyChanging();
					this._StreetAndNo = value;
					this.SendPropertyChanged("StreetAndNo");
					this.OnStreetAndNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(20)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraderType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TraderType
		{
			get
			{
				return this._TraderType;
			}
			set
			{
				if ((this._TraderType != value))
				{
					this.OnTraderTypeChanging(value);
					this.SendPropertyChanging();
					this._TraderType = value;
					this.SendPropertyChanged("TraderType");
					this.OnTraderTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Traders_Buyers", Storage="_Buyers", ThisKey="Id", OtherKey="TraderID")]
		public EntitySet<Buyers> Buyers
		{
			get
			{
				return this._Buyers;
			}
			set
			{
				this._Buyers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Traders_PrivatePersons", Storage="_PrivatePersons", ThisKey="Id", OtherKey="TraderID")]
		public EntitySet<PrivatePersons> PrivatePersons
		{
			get
			{
				return this._PrivatePersons;
			}
			set
			{
				this._PrivatePersons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Traders_Sellers", Storage="_Sellers", ThisKey="Id", OtherKey="TraderID")]
		public EntitySet<Sellers> Sellers
		{
			get
			{
				return this._Sellers;
			}
			set
			{
				this._Sellers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Buyers(Buyers entity)
		{
			this.SendPropertyChanging();
			entity.Traders = this;
		}
		
		private void detach_Buyers(Buyers entity)
		{
			this.SendPropertyChanging();
			entity.Traders = null;
		}
		
		private void attach_PrivatePersons(PrivatePersons entity)
		{
			this.SendPropertyChanging();
			entity.Traders = this;
		}
		
		private void detach_PrivatePersons(PrivatePersons entity)
		{
			this.SendPropertyChanging();
			entity.Traders = null;
		}
		
		private void attach_Sellers(Sellers entity)
		{
			this.SendPropertyChanging();
			entity.Traders = this;
		}
		
		private void detach_Sellers(Sellers entity)
		{
			this.SendPropertyChanging();
			entity.Traders = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Buyers")]
	public partial class Buyers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _TraderID;
		
		private EntitySet<Invoice> _Invoices;
		
		private EntityRef<Traders> _Traders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTraderIDChanging(int value);
    partial void OnTraderIDChanged();
    #endregion
		
		public Buyers()
		{
			this._Invoices = new EntitySet<Invoice>(new Action<Invoice>(this.attach_Invoices), new Action<Invoice>(this.detach_Invoices));
			this._Traders = default(EntityRef<Traders>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraderID", DbType="Int NOT NULL")]
		public int TraderID
		{
			get
			{
				return this._TraderID;
			}
			set
			{
				if ((this._TraderID != value))
				{
					if (this._Traders.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTraderIDChanging(value);
					this.SendPropertyChanging();
					this._TraderID = value;
					this.SendPropertyChanged("TraderID");
					this.OnTraderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Buyers_Invoice", Storage="_Invoices", ThisKey="Id", OtherKey="BuyerId")]
		public EntitySet<Invoice> Invoices
		{
			get
			{
				return this._Invoices;
			}
			set
			{
				this._Invoices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Traders_Buyers", Storage="_Traders", ThisKey="TraderID", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Traders Traders
		{
			get
			{
				return this._Traders.Entity;
			}
			set
			{
				Traders previousValue = this._Traders.Entity;
				if (((previousValue != value) 
							|| (this._Traders.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Traders.Entity = null;
						previousValue.Buyers.Remove(this);
					}
					this._Traders.Entity = value;
					if ((value != null))
					{
						value.Buyers.Add(this);
						this._TraderID = value.Id;
					}
					else
					{
						this._TraderID = default(int);
					}
					this.SendPropertyChanged("Traders");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.Buyers = this;
		}
		
		private void detach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.Buyers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PrivatePersons")]
	public partial class PrivatePersons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _TraderID;
		
		private string _PESEL;
		
		private EntityRef<Traders> _Traders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTraderIDChanging(int value);
    partial void OnTraderIDChanged();
    partial void OnPESELChanging(string value);
    partial void OnPESELChanged();
    #endregion
		
		public PrivatePersons()
		{
			this._Traders = default(EntityRef<Traders>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraderID", DbType="Int NOT NULL")]
		public int TraderID
		{
			get
			{
				return this._TraderID;
			}
			set
			{
				if ((this._TraderID != value))
				{
					if (this._Traders.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTraderIDChanging(value);
					this.SendPropertyChanging();
					this._TraderID = value;
					this.SendPropertyChanged("TraderID");
					this.OnTraderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESEL", DbType="NVarChar(20)")]
		public string PESEL
		{
			get
			{
				return this._PESEL;
			}
			set
			{
				if ((this._PESEL != value))
				{
					this.OnPESELChanging(value);
					this.SendPropertyChanging();
					this._PESEL = value;
					this.SendPropertyChanged("PESEL");
					this.OnPESELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Traders_PrivatePersons", Storage="_Traders", ThisKey="TraderID", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Traders Traders
		{
			get
			{
				return this._Traders.Entity;
			}
			set
			{
				Traders previousValue = this._Traders.Entity;
				if (((previousValue != value) 
							|| (this._Traders.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Traders.Entity = null;
						previousValue.PrivatePersons.Remove(this);
					}
					this._Traders.Entity = value;
					if ((value != null))
					{
						value.PrivatePersons.Add(this);
						this._TraderID = value.Id;
					}
					else
					{
						this._TraderID = default(int);
					}
					this.SendPropertyChanged("Traders");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sellers")]
	public partial class Sellers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _TraderID;
		
		private string _BankAccount;
		
		private string _Bank;
		
		private string _SWIFT;
		
		private EntitySet<Invoice> _Invoices;
		
		private EntityRef<Traders> _Traders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTraderIDChanging(int value);
    partial void OnTraderIDChanged();
    partial void OnBankAccountChanging(string value);
    partial void OnBankAccountChanged();
    partial void OnBankChanging(string value);
    partial void OnBankChanged();
    partial void OnSWIFTChanging(string value);
    partial void OnSWIFTChanged();
    #endregion
		
		public Sellers()
		{
			this._Invoices = new EntitySet<Invoice>(new Action<Invoice>(this.attach_Invoices), new Action<Invoice>(this.detach_Invoices));
			this._Traders = default(EntityRef<Traders>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraderID", DbType="Int NOT NULL")]
		public int TraderID
		{
			get
			{
				return this._TraderID;
			}
			set
			{
				if ((this._TraderID != value))
				{
					if (this._Traders.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTraderIDChanging(value);
					this.SendPropertyChanging();
					this._TraderID = value;
					this.SendPropertyChanged("TraderID");
					this.OnTraderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccount", DbType="NVarChar(50)")]
		public string BankAccount
		{
			get
			{
				return this._BankAccount;
			}
			set
			{
				if ((this._BankAccount != value))
				{
					this.OnBankAccountChanging(value);
					this.SendPropertyChanging();
					this._BankAccount = value;
					this.SendPropertyChanged("BankAccount");
					this.OnBankAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="NVarChar(255)")]
		public string Bank
		{
			get
			{
				return this._Bank;
			}
			set
			{
				if ((this._Bank != value))
				{
					this.OnBankChanging(value);
					this.SendPropertyChanging();
					this._Bank = value;
					this.SendPropertyChanged("Bank");
					this.OnBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWIFT", DbType="NVarChar(20)")]
		public string SWIFT
		{
			get
			{
				return this._SWIFT;
			}
			set
			{
				if ((this._SWIFT != value))
				{
					this.OnSWIFTChanging(value);
					this.SendPropertyChanging();
					this._SWIFT = value;
					this.SendPropertyChanged("SWIFT");
					this.OnSWIFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sellers_Invoice", Storage="_Invoices", ThisKey="Id", OtherKey="SellerId")]
		public EntitySet<Invoice> Invoices
		{
			get
			{
				return this._Invoices;
			}
			set
			{
				this._Invoices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Traders_Sellers", Storage="_Traders", ThisKey="TraderID", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Traders Traders
		{
			get
			{
				return this._Traders.Entity;
			}
			set
			{
				Traders previousValue = this._Traders.Entity;
				if (((previousValue != value) 
							|| (this._Traders.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Traders.Entity = null;
						previousValue.Sellers.Remove(this);
					}
					this._Traders.Entity = value;
					if ((value != null))
					{
						value.Sellers.Add(this);
						this._TraderID = value.Id;
					}
					else
					{
						this._TraderID = default(int);
					}
					this.SendPropertyChanged("Traders");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.Sellers = this;
		}
		
		private void detach_Invoices(Invoice entity)
		{
			this.SendPropertyChanging();
			entity.Sellers = null;
		}
	}
}
#pragma warning restore 1591
