<?xml version="1.0" encoding="utf-8"?><Database Name="InvoiceMakerDB" Class="InvoiceMakerDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=InvoiceMakerDB;Integrated Security=True" SettingsObjectName="InvoiceMaker.Properties.Settings" SettingsPropertyName="InvoiceMakerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Invoices" Member="Invoices">
    <Type Name="Invoices">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SaleDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Place" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SellerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BuyerType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PaymentDeadline" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SellerSignature" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BuyerSignature" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Invoices_Items" Member="Items" ThisKey="Id" OtherKey="InvoiceId" Type="Items" />
      <Association Name="Sellers_Invoices" Member="Sellers" ThisKey="SellerId" OtherKey="Id" Type="Sellers" IsForeignKey="true" />
      <Association Name="Buyers_Invoices" Member="Buyers" ThisKey="BuyerId" OtherKey="Id" Type="Buyers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Items">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VAT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Netto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Brutto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Invoices_Items" Member="Invoices" ThisKey="InvoiceId" OtherKey="Id" Type="Invoices" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrivatePersons" Member="PrivatePersons">
    <Type Name="PrivatePersons">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TraderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PESEL" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Trader_PrivatePersons" Member="Traders" ThisKey="TraderID" OtherKey="Id" Type="Traders" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sellers" Member="Sellers">
    <Type Name="Sellers">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TraderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BankAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bank" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SWIFT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Sellers_Invoices" Member="Invoices" ThisKey="Id" OtherKey="SellerId" Type="Invoices" />
      <Association Name="Trader_Sellers" Member="Traders" ThisKey="TraderID" OtherKey="Id" Type="Traders" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Buyers" Member="Buyers">
    <Type Name="Buyers">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TraderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Buyers_Invoices" Member="Invoices" ThisKey="Id" OtherKey="BuyerId" Type="Invoices" />
      <Association Name="Trader_Buyers" Member="Traders" ThisKey="TraderID" OtherKey="Id" Type="Traders" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Traders" Member="Traders">
    <Type Name="Traders">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VATID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="StreetAndNo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TraderType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Trader_PrivatePersons" Member="PrivatePersons" ThisKey="Id" OtherKey="TraderID" Type="PrivatePersons" />
      <Association Name="Trader_Sellers" Member="Sellers" ThisKey="Id" OtherKey="TraderID" Type="Sellers" />
      <Association Name="Trader_Buyers" Member="Buyers" ThisKey="Id" OtherKey="TraderID" Type="Buyers" />
    </Type>
  </Table>
</Database>